include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    # カスケード記法を強制しない
    cascade_invocations: false

    # パッケージ内のimportは相対パスで書く
    prefer_relative_imports: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
    todo: ignore
  plugins:
    - custom_lint

custom_lint:
  rules:
